server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone:  ${EUREKA_URI:http://89.104.68.220:8761/eureka/}
    enabled: true

spring:
  application:
    name: dialog-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:89.104.68.220:9094}

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: ${DB_URL:jdbc:postgresql://89.104.68.220:5432/dialog_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Psql7355}
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: dialog_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS dialog_schema
      connection-timeout: 10000

app:
  kafka:
    kafkaMessageTopic: "message-topic"
    kafkaGroupId: "dialog-service"

  address: ${SERVER_ADDRESS:89.104.68.220}

  jwt:
    secret: "secretKey"
  request-validation:
    enabled: true
    validator-path: "http://89.104.68.220:8081/api/v1/auth/validate"
